# Github Actions

# Jobs for testing library before accepting a Pull Request

name: Build-And-Test

on:
  push
#  pull_request:
#    branches:
#    - 'main'
#    - 'develop'
#    - 'release/**'

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Build
      run: |
        make

    - name: Test
      run: |
        make test

    - name: Memcheck
      run: |
        sudo apt install -y valgrind
        make memcheck
