# Github Actions

# Jobs for testing library before accepting a Pull Request

name: Run Unit Tests

on:
  pull_request:
    branches:
    - 'main'
    - 'develop'
    - 'release/**'

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: build
      run: |
        make

    - name: test
      run: |
        make test
